### ISSUE TITLE
Amazing project! I seem to have issues testing your project.

### ISSUE THREAD

**Issue by animemandir** [rayriffy/rayriffy-h#1894]
I never worked or even tries nextjs or nx, am completely new. Pardon my ignorance if I ask something childish or obvious.

![image](https://user-images.githubusercontent.com/78192713/133931454-59e92a7e-918d-4879-9b18-6d6e2dba592a.png)

How do I even run this!! What is the problem, does this not run with simple cmds like nx run, nx test or nx serve.
It would be great if you show what needs to be done in order to run.test or build this after cloning your repo.

**Comment by animemandir** [comment]
Why is this happening? Please correct me if am doing something wrong.
![image](https://user-images.githubusercontent.com/78192713/134765613-a1632ccf-a0dc-4310-9c39-75ce75e5affb.png)

**Comment by rayriffy** [comment]
Sorry, I haven't look into this repository for a while. Those NX should not be in `app/web-next` what you should do is to execute it proper Nx. and it's my fault to not update readme at all as well. and i have already moved to pnpm already so here's new guide for you.
.
At repository root, install dependencies with `npx pnpm install`, then pre-generate page pagination with `npx pnpm generateChunks`. and call `npx pnpm nx build web-next` for development server

**Comment by animemandir** [comment]
Yeah, thanks everything is working fine except this - 
![image](https://user-images.githubusercontent.com/78192713/138059560-c843d10d-51f7-4336-86f6-8bc7122fe8f5.png)
What is happening here, am not able to fix this. And also I was hoping to add a feature - 'download'.
That would work as simple "save as pdf". The total visible, collapsed, or yet to scroll content would be "saved as pdf" onclick.
react to pdf libs ain't working on this, are there nextjs libs or packages that would do this trick?

**Comment by animemandir** [comment]
Hey Riffy, i made a dowload button and few ui tweaks. i want to test deploy it o vercel but i think am doing something wrong there. I never worked with vercel before so i trued reading docs and all but it didn't help much.
i imported the git repo in vercel and tried build. The build failed with an error. Here is the log:
![image](https://user-images.githubusercontent.com/78192713/143667959-35898b9d-2ec1-4d48-8967-4e19307d3f8a.png)

![image](https://user-images.githubusercontent.com/78192713/143667973-228e20c1-9b9b-4d77-8851-71a0126f3ae0.png)

![image](https://user-images.githubusercontent.com/78192713/143667980-002bc2c3-f1a4-4cdf-9431-c709f71197be.png)

![image](https://user-images.githubusercontent.com/78192713/143667994-224faae9-b13d-48e3-a60f-057e8ed2bd4c.png)

Am really sorry for being annoying. T_T

**Comment by animemandir** [comment]
Nice that you updated the project, but what's up with the databases in env?

**Comment by rayriffy** [comment]
Hey, a lot of changes happened during this time. I've simplified tech stack back from monorepo to just regular Next project.

API has been moved to use API from [Hifumin](https://hifumin.app) as well, and it has been protected with Cloudflare Enterprise. Even my `pnpm build:data` command to prefetch all hentais already optimized with local file caching, but sometimes when you're deploying fresh from CI and has to fetch 1000+ hentais at the same time to API you could get into an issue with Cloudflare bot challenge response.

To reduce load, I spin-up my own database for local caching but it will be removed soon. Last few weeks I made it optionally to have `DATABASE_URL` running with `build:data` command but if you wanted to you could spin up your own Postgres database, properly configure [connection URL](https://www.prisma.io/docs/concepts/database-connectors/postgresql#connection-url) and run `pnpm prisma:deploy` once to generate database and tables.
