### ISSUE TITLE
Deployment is down or moved?

### ISSUE THREAD

**Issue by SaltyAom** [rayriffy/rayriffy-h#1896]
Can't access [h.rayriffy.com](https://h.rayriffy.com)
<img width="1624" alt="Screen Shot 2564-12-20 at 10 57 31" src="https://user-images.githubusercontent.com/35027979/146709759-d2c1b4e0-33a8-40f3-a41b-870bb1fb7736.png">

**Comment by rayriffy** [comment]
Cost is not viable right now (billing lsat time before I stop deployment was 3000$). I have better architecture to reduce cost in the plan already, but it is going to be a long run work. Might finished around next few months.

**Comment by mishailovic** [comment]
> Cost is not viable right now (billing last time before I stop deployment was 3000$). I have better architecture to reduce cost in the plan already, but it is going to be a long run work. Might finished around next few months.

How about to deploy it on a free deploy solution like heroku?

**Comment by rayriffy** [comment]
It's been a while but the deployments is now backed up again. Happy Christmas!

**Comment by mishailovic** [comment]
> It's been a while but the deployments is now backed up again. Happy Christmas!

Best present for the Christmas and New Year, thanks @rayriffy and happy holidays to you
