### ISSUE TITLE
[idea] : I would like to add the login section

### ISSUE THREAD

**Issue by thanawatgulati** [rayriffy/rayriffy-h#946]
**issues** : Sometimes I may find stories that I like. But when I come back to read it again, I don't find it (in other browsers or incognito mode)

**offer** :  I want to offer a login section to collect my favorites. 😅

**Comment by rayriffy** [comment]
I think this feature is already implemented it called collection instead and our stack does not have any back-end for user and authentication at all. Everything is done by client-side.
